// This file was generated by build.rs

enum MouseButton: UInt8 {
    case
    left,
    right,
    middle
}

extension MouseButton {
    func toString() -> StaticString {
        switch self {
            case .left: return "Left"
            case .right: return "Right"
            case .middle: return "Middle"
        }
    }
}
