// This file was generated by build.rs

#[repr(u8)]
#[derive(Clone, Copy, Debug)]
pub enum CommandCode {
    MouseMoveTo = 0,
    MouseMoveRelative = 1,
    MouseDown = 2,
    MouseUp = 3,
    MouseClick = 4,
    MouseNthClick = 5,
    MouseScrollX = 6,
    MouseScrollY = 7,
    KeyDown = 8,
    KeyUp = 9,
    KeyClick = 10,
}

impl std::convert::TryFrom<u8> for CommandCode {
    type Error = ();

    fn try_from(b: u8) -> Result<Self, Self::Error> {
        use CommandCode::*;
        match b {
            0 => Ok(MouseMoveTo),
            1 => Ok(MouseMoveRelative),
            2 => Ok(MouseDown),
            3 => Ok(MouseUp),
            4 => Ok(MouseClick),
            5 => Ok(MouseNthClick),
            6 => Ok(MouseScrollX),
            7 => Ok(MouseScrollY),
            8 => Ok(KeyDown),
            9 => Ok(KeyUp),
            10 => Ok(KeyClick),
            _ => Err(()),
        }
    }
}
