// This file was generated by build.rs

use bitflags::bitflags;

bitflags! {
    pub struct Flags: u8 {
        const NULL = 0;
        const CAPS_LOCK = 1;
        const SHIFT = 2;
        const CONTROL = 4;
        const ALT = 8;
        const COMMAND = 16;
    }
}
