// This file was generated by build.rs

#[repr(u8)]
#[derive(Clone, Copy, Debug)]
pub enum MouseButton {
    Left = 0,
    Right = 1,
    Middle = 2,
}

impl std::str::FromStr for MouseButton {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "mouseleft" => Ok(MouseButton::Left),
            "mouseright" => Ok(MouseButton::Right),
            "mousemiddle" => Ok(MouseButton::Middle),
            _ => Err(()),
        }
    }
}
