enumeration!(CommandCode, [
    (Delay, "Delay"),
    (KeyDown, "Key Down"),
    (KeyUp, "Key Up"),
    (KeyClick, "Key Click"),
    (MouseMoveRel, "Mouse Move Relative"),
    (MouseMoveAbs, "Mouse Move Absolute"),
    (MouseScroll, "Mouse Scroll"),
    (MouseDown, "Mouse Down"),
    (MouseUp, "Mouse Up"),
    (MouseClick, "Mouse Click"),
    (AsciiCharDown, "ASCII Char Down"),
    (AsciiCharUp, "ASCII Char Up"),
    (AsciiChar, "ASCII Char"),
    (AsciiString, "ASCII String"),
    (UnicodeCharDown, "Unicode Char Down"),
    (UnicodeCharUp, "Unicode Char Up"),
    (UnicodeChar, "Unicode Char"),
    (UnicodeString, "Unicode String"),
]);
