// This file was generated by build.rs

#[repr(u8)]
#[derive(Copy, Clone, Debug)]
pub enum CommandCode {
    KeyDown,
    KeyUp,
    KeyClick,
    MouseMoveRel,
    MouseMoveAbs,
    MouseWarp,
    MouseScroll,
    MouseDown,
    MouseUp,
    MouseClick,
}

impl CommandCode {
    pub const COUNT: u8 = 10;
}
