// This file was generated by build.rs

export const MOUSE_MOVE_TO = 0;
export const MOUSE_MOVE_RELATIVE = 1;
export const MOUSE_DOWN = 2;
export const MOUSE_UP = 3;
export const MOUSE_CLICK = 4;
export const MOUSE_NTH_CLICK = 5;
export const MOUSE_SCROLL_X = 6;
export const MOUSE_SCROLL_Y = 7;
export const KEY_DOWN = 8;
export const KEY_UP = 9;
export const KEY_CLICK = 10;
