pub const COMMANDS: [&str; 18] = [
    "Delay",
    "Key down",
    "Key up",
    "Key click",
    "Mouse move rel",
    "Mouse move abs",
    "Mouse scroll",
    "Mouse down",
    "Mouse up",
    "Mouse click",
    "ASCII char down",
    "ASCII char up",
    "ASCII char",
    "ASCII string",
    "Unicode char down",
    "Unicode char up",
    "Unicode char",
    "Unicode string",
];
