pub const COMMANDS: [&str; 14] = [
    "Delay",
    "Key down",
    "Key up",
    "Key click",
    "Mouse move rel",
    "Mouse move abs",
    "Mouse scroll",
    "Mouse down",
    "Mouse up",
    "Mouse click",
    "ASCII char",
    "ASCII string",
    "Unicode char",
    "Unicode string",
];
