pub const KEYS: [&str; 109] = [
    // Modifier keys
    "Caps Lock",
    "Shift",
    "Control",
    "Alt",
    "Meta", // Command on macOS. Windows key on Windows.
    "Control or Meta", // Command on macOS. Control on Windows.
    "Right Shift",
    "Right Control",
    "Right Alt",
    "Right Meta", // Command on macOS. Windows key on Windows.
    "Right Control or Meta", // Command on macOS. Control on Windows.
    "Fn",

    // Controls and symbols
    "Return or Enter",
    "Escape",
    "Delete or Backspace",
    "Forward Delete",
    "Tab",
    "Space",
    "Minus",
    "Equal",
    "Left Bracket",
    "Right Bracket",
    "Backslash",
    "Semicolon",
    "Quote",
    "Grave",
    "Comma",
    "Period",
    "Slash",

    // Arrow keys
    "Up Arrow",
    "Right Arrow",
    "Down Arrow",
    "Left Arrow",
    "Page Up",
    "Page Down",
    "Home",
    "End",

    // Letter keys
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",

    // Number keys
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",

    // Number pad numbers
    "Numpad 0",
    "Numpad 1",
    "Numpad 2",
    "Numpad 3",
    "Numpad 4",
    "Numpad 5",
    "Numpad 6",
    "Numpad 7",
    "Numpad 8",
    "Numpad 9",

    // Number pad keys
    "Numpad Clear",
    "Numpad Equals",
    "Numpad Divide",
    "Numpad Multiply",
    "Numpad Minus",
    "Numpad Plus",
    "Numpad Enter",
    "Numpad Decimal",

    // Function keys
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",

    // Media controls
    "Fast-Forward",
    "Rewind",
    "Play/Pause",
    "Volume Up",
    "Volume Down",
    "Mute",
];
